# Generated by Django 4.2.7 on 2023-11-09 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 17, 42, 5, 477605, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(max_length=252, unique_for_date='publish'),
        ),
    ]
