# Generated by Django 4.2.7 on 2023-11-08 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 5, 15, 59, 225394, tzinfo=datetime.timezone.utc)),
        ),
    ]
