# Generated by Django 4.2.7 on 2023-11-09 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_publish_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 22, 44, 39, 222735)),
        ),
    ]
